#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

exchange_rates:
    path: /api/exchange-rates/{startDate}/{endDate}
    controller: App\Controller\ExchangeRatesController::getRates
    methods:  GET    

exchange_rates_single:
    path: /api/exchange-rates/{startDate}
    controller: App\Controller\ExchangeRatesController::getRates
    methods:  GET     

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index
